config/routes.rb
Rails.application.routes.draw do

  root "welcome#home"

  resources :requests

  post "requests/:id" => "requests#done_toggle"

  get "/search" => "requests#search"

end

app/models/request.rb
class Request < ActiveRecord::Base

  validates_presence_of :name, :email

  after_initialize :set_default

  def self.search(term, page)
    paginate :per_page => 10, :page => page,
            :conditions => ["name ilike ? OR message ilike ? OR email ilike ? ", "%#{term}%", "%#{term}%", "%#{term}%"],
            :order => "done desc"
  end

  private

  def set_default
    self.done = "Not Done" unless self.done == "Done"

  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  before_action :find_request, only: [:edit, :update, :destroy, :show]
  def index
    @requests = Request.order("done desc")
  end

  def new
    @request = Request.new
  end

  def show
  end

  def create
    request_params = params.require(:request).permit(:name, :email, :department, :message)
    @request = Request.new request_params
    if @request.save
      redirect_to requests_path
    else
      flash[:alert] = "Failed to create.  Please correct errors"
      render :new
    end
  end

  def edit
  end

  def update
    request_params = params.require(:request).permit(:name, :email, :department, :message)
    if @request.update request_params
      redirect_to request_path(@request), notice: "Request Updated"
    else
      render :edit
    end
  end

  def destroy
    @request.destroy
    redirect_to requests_path, notice: "Request Removed"
  end

  def done_toggle
    @request = Request.find params[:id]
    if @request.done == "Done"
      @request.done = "Not Done"
      @request.save
    else @request.done = "Done"
      @request.save
    end
    redirect_to requests_path
  end

  def search
    @q = params.permit(:q)
    @requests = Request.where(["name ilike ? OR message ilike ? OR email ilike ? ", "%#{@q[:q]}%", "%#{@q[:q]}%", "%#{@q[:q]}%"]).paginate(:page => params[:page]).order("done desc")
  end

  def search2
    @q = params.permit(:q)
    @q = @q[:q]


  end

  private

  def find_request
    @request = Request.find params[:id]
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def home
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Quiz1</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= link_to "Home", root_path %> |
<%= link_to "All Requests", requests_path %> |
<%= link_to "Add a Request", new_request_path %>
<%= yield %>

</body>
</html>

app/views/requests/_form.html.erb
<% if @request.errors.any? %>
  <% @request.errors.full_messages.each do |msg| %>
    <p><%= msg %></p>
  <% end %>
<% end %>

<%= form_for @request do |f| %>

  <div>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div>
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>
  <div>
    <%= f.label :department %> |
    <%= f.radio_button :department, "Sales" %> Sales |
    <%= f.radio_button :department, "Marketing" %> Marketing |
    <%= f.radio_button :department, "Technical" %> Technical
  </div>
  <div>
    <%= f.label :message %>
    <%= f.text_area :message %>
  </div>
  <%= f.submit %>

<% end %>

app/views/requests/edit.html.erb
<h1> Update Your Request</h1>

<%= render "form" %>

app/views/requests/index.html.erb
<h1> Support Requests</h1>

<%= form_tag "/search", method: "get" do %>
  <%= label_tag :q, "Search" %>
  <%= text_field_tag :q, params[:q] %>
  <%= submit_tag "Search" %>
<% end %>
<table>
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th>Department</th>
    <th>Message</th>
    <th>Actions</th>
  </tr>
  <% @requests.each do |request| %>
    <tr>
      <td> <%= request.name %></td>
      <td> <%= mail_to request.email %></td>
      <td> <%= request.department %></td>
      <td> <%= request.message %></td>
      <td> <%= link_to "Edit", edit_request_path(request) %>
           <%= link_to "Remove", request_path(request),
                method: :delete, data: {confirm: "Confirm Removal"} %>
           <%= link_to request.done, request_path(request), method: :post %></td>
    </tr>
  <% end %>
</table>

app/views/requests/new.html.erb
<h1> Submit a Support Request</h1>

<%= render "form" %>

app/views/requests/search.html.erb
<h1> Search Results</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th>Department</th>
    <th>Message</th>
    <th>Actions</th>
  </tr>

  <% @requests.each do |request| %>
    <tr>
      <td> <%= request.name %></td>
      <td> <%= mail_to request.email %></td>
      <td> <%= request.department %></td>
      <td> <%= request.message %></td>
      <td> <%= link_to "Edit", edit_request_path(request) %>
           <%= link_to "Remove", request_path(request),
                method: :delete, data: {confirm: "Confirm Removal"} %>
           <%= link_to request.done, request_path(request), method: :post %></td>
    </tr>
  <% end %>
</table>

app/views/requests/search2.html.erb
<%= params.inspect %>

app/views/requests/show.html.erb
<br><br>Requestor: <%= @request.name %><br>

<br>Email: <%= @request.email %><br>

<br>Department: <%= @request.department %><br><br>

Message: <%= @request.message %>

app/views/welcome/home.html.erb
<h1> Hello World!</h1>